name: saleassist_video_tiles
description: "Saleassist Video Tiles — reusable video tiles with carousel, caching, and product click callbacks."
version: 0.0.1
homepage: https://github.com/yash-g-dev/Saleassist-video-tiles
repository: https://github.com/yash-g-dev/Saleassist-video-tiles
issue_tracker: https://github.com/yash-g-dev/Saleassist-video-tiles/issues
documentation: https://github.com/yash-g-dev/Saleassist-video-tiles#readme

topics:
  - flutter
  - video
  - carousel
  - widgets
  - ui

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.22.0"

# Let pub.dev know which platforms you support
platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:

dependencies:
  flutter:
    sdk: flutter

  chewie: ^1.11.3
  video_player: ^2.10.0

  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  visibility_detector: ^0.4.0+2
  dio: ^5.8.0+1
  flutter_cache_manager: ^3.4.1
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # If you later add demo images/fonts, declare them here.
  # assets:
  #   - assets/preview.png

# Optional but recommended: show screenshots on pub.dev (add files to repo first)
# screenshots:
#   - description: "Horizontal video tiles with product quick actions"
#     path: assets/preview.png
#   - description: "Fullscreen player with controls"
#     path: assets/fullscreen.png
